# Generated by Django 3.0 on 2020-11-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdataapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='section_name',
        ),
    ]
